application:
  name: hellok8s
  hellok8s:
    image: oneformanew.azurecr.io/hellok8s:v6
    replicas: 3
    message: "It works with Helm Values[v2]!888"
    database:
      url: "http://DB_ADDRESS_DEFAULT"
      password: "db_password"
  nginx:
    image: nginx
    replicas: 2